# Generated by Django 2.2 on 2021-04-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_remove_tweet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
