# Generated by Django 2.2 on 2021-04-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
